# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "หน้าแรก"
  url = "#hero"
  weight = 1


[[main]]
  name = "พิธีการศุลกากร"
  url = "pages/import-export/"
  weight = 20

[[main]]
  parent = "พิธีการศุลกากร"
  name = "การนำเข้าสินค้า"
  url = "pages/import/"
  weight = 21

[[main]]
  parent = "พิธีการศุลกากร"
  name = "การส่งออกสินค้า"
  url = "pages/export/"
  weight = 22
  
[[main]]
  parent = "พิธีการศุลกากร"
  name = "สินค้าถ่ายลำ/ผ่านแดน"
  url = "pages/transit/"
  weight = 23
[[main]]
  parent ="พิธีการศุลกากร"
  name = "สิทธิประโยชน์ทางภาษี"
  url = "pages/tax-inc/"
  weight = 24
[[main]]
  parent = "พิธีการศุลกากร"
  name = "สิทธิพิเศษทางการค้า"
  url = "pages/fta/"
  weight = 25
[[main]]
  parent = "พิธีการศุลกากร"
  name = "A.T.A. CARNET"
  url = "pages/ata-carnet/"
  weight = 26
[[main]]
  parent = "พิธีการศุลกากร"
  name = "การปฏิบัติพิธีการศุลกากร"
  url = "pages/clearance/"
  weight = 27


[[main]]
  name = "เรื่องน่ารู้"
  url = "pages/"
  weight = 30


[[main]]
  parent = "เรื่องน่ารู้"
  name = "ของควบคุมการนำเข้า-ส่งออก"
  url = "pages/restricted/"
  weight = 31

[[main]]
  parent = "เรื่องน่ารู้"
  name = "พิกัดศุลกากร"
  url = "pages/tariff/"
  weight = 32
  
[[main]]
  parent = "เรื่องน่ารู้"
  name = "ราคาศุลกากร"
  url = "pages/price/"
  weight = 33

[[main]]
  parent = "เรื่องน่ารู้"
  name = "กรมศุลกากร"
  url = "pages/customs/"
  weight = 41

[[main]]
  parent = "เรื่องน่ารู้"
  name = "ผู้ประกอบการ"
  url = "pages/company/"
  weight = 42

[[main]]
  parent = "เรื่องน่ารู้"
  name = "ข่าวสาร"
  url = "post/news/"
  weight = 49

[[main]]
  parent = "เรื่องน่ารู้"
  name = "Reference data"
  url = "https://ecs-support.github.io/KM/reference/"
  weight = 55





[[main]]

  name = "ประกาศ/กฎหมาย"
  url = "post/law/"
  weight = 60

[[main]]
  parent = "ประกาศ/กฎหมาย"
  name = "ประกาศกรมศุลกากร"
  url = "post/law/customs/"
  weight = 61

[[main]]
  parent = "ประกาศ/กฎหมาย"
  name = "ประกาศกระทรวง"
  url = "post/law/ministry/"
  weight = 62

[[main]]
  parent = "ประกาศ/กฎหมาย"
  name = "ประกาศหน่วยงานอื่น ๆ"
  url = "post/law/oga/"
  weight = 63


[[main]]
  name = "คลังความรู้"
  url = "pages/knowledge/"
  hasChildren = true


[[main]]
  parent = "คลังความรู้"
  name = "ISO 27001"
  url = "pages/knowledge/iso/"


[[main]]
  parent = "คลังความรู้"
  name = "เอกสารเผยแพร่"
  url = "pages/docs/section/"
 

[[main]]
  parent = "คลังความรู้"
  name = "บทความน่ารู้"
  url = "post/knowledge/"
 

[[main]]
  parent = "คลังความรู้"
  name = "FAQ"
  url = "faq/"








